# Generated by Django 6.0.2 on 2026-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="doctor_check_in_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the doctor checked in for this queue",
                null=True,
            ),
        ),
    ]
