# Generated by Django 5.0.14 on 2025-12-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientqueue",
            name="consultation_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientqueue",
            name="consultation_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
