# Generated by Django 5.0.14 on 2025-12-04 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_patient_emergency_contact_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("ADMIN", "Admin"),
                ],
                default="PATIENT",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="nurse_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nurses",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "nurses",
            },
        ),
    ]
