# Generated by Django 5.0.6 on 2026-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_delete_doctoravailability"),
        ("doctors", "0002_doctoravailability"),
        ("patients", "0002_patientform"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "status"], name="appt_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "appointment_date"], name="appt_doctor_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"], name="appt_patient_date_idx"
            ),
        ),
    ]
