# Generated by Django 6.0.2 on 2026-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientform"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientform",
            name="symptoms",
            field=models.TextField(blank=True, help_text="List of selected symptoms"),
        ),
    ]
