# Generated by Django 6.0.2 on 2026-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patientform_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientform",
            name="medical_history_options",
            field=models.TextField(
                blank=True, help_text="Selected medical history checklist items"),
        ),
        migrations.AddField(
            model_name="patientform",
            name="allergy_options",
            field=models.TextField(
                blank=True, help_text="Selected allergy checklist items"),
        ),
    ]
