# Generated by Django 5.0.14 on 2025-12-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
        ("appointments", "0003_delete_doctoravailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_duration",
                    models.IntegerField(default=30, help_text="Duration in minutes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
                "db_table": "doctor_availability",
                "unique_together": {("doctor", "day_of_week")},
            },
        ),
    ]
