# Generated by Django 6.0.2 on 2026-02-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctoravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Doctor's profile picture",
                null=True,
                upload_to="doctor_photos/",
            ),
        ),
    ]
